# Generated by Django 6.0.4 on 2026-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('na', 'N/A')], default='na', max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='You must provide specific name of book', max_length=100, unique=True, verbose_name='Book name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique_for_month='created_at'),
        ),
    ]
